import { createContext, useContext } from 'react'

export const LANGUAGE_KEY = 'tete-language-v1'
const I18nContext = createContext({ language: 'en', setLanguage: () => {}, t: (key) => key })

const en = {
  practice: 'Practice', viewProgress: 'View progress', backHome: 'Back to home', backModes: 'Back to practice modes', learningMode: 'Learning Mode', assessmentMode: 'Assessment Mode', chooseMode: 'Choose a mode', chooseLearning: 'Choose Learning Mode', chooseAssessment: 'Choose Assessment Mode',
  nextStep: 'Your next step', continueLearning: 'Continue learning', chooseTopic: 'Choose another topic instead', learningDescription: 'Practise with hints, feedback, and revision.',
  education: 'For education only. Not for clinical diagnosis.', reviewStatus: 'Case content expert review:', notReviewed: 'Not yet reviewed', frenchNotice: 'French translations are provisional and have not been reviewed by a bilingual ECG educator.',
  backLearning: 'Back to Learning Mode', backAssessment: 'Back to Assessment Mode', foundations: 'Foundations', readSystematically: 'Read the ECG systematically.', learningCaseIntro: 'Use hints when you need them, then revise after feedback. Check rate, sinus origin, intervals, axis, and ST/T findings.', assessmentCaseIntro: 'The diagnosis and topic remain hidden until you submit. Check rate, sinus origin, intervals, axis, and ST/T findings.',
  schematic: 'Schematic educational ECG', resting: '12-lead resting ECG', rhythmStrip: 'II rhythm strip', figureNote: 'Purpose-built schematic—not a patient recording. Horizontal grid: 1 small box = 40 ms; vertical calibration pulse = 10 mm (1 mV).', expertReview: 'Expert review:',
  whatSee: 'What do you see?', hintsLearning: 'Hints are available and revision carries no rating penalty.', hintsAssessment: 'Hints and answers remain hidden until submission.', notSurePrompt: 'Choose “Not sure” whenever needed.', chooseFinding: 'Choose the best finding', selectAnswer: 'Select an answer', notSure: 'Not sure', showHint: 'Show hint', hideHint: 'Hide hint', tryThis: 'Try this:',
  explain: 'Explain your interpretation', freeNotScored: 'This free text is not scored.', placeholder: 'I think this ECG shows… because…', structuredOnly: 'Only structured answers contribute to the weighted percentage.', submitPractice: 'Submit practice', submitAssessment: 'Submit assessment',
  yourFocus: 'Your focus', fullWorkflow: 'Complete the full interpretation as usual. This Learning Mode session cannot change your rating.', reviewPractice: 'Review practice—does not change your rating.',
  topicSearch: 'What would you like to learn?', searchTopics: 'Search ECG topics', searchPlaceholder: 'Try “slow heart rate”, “NSR”, or “rhythm”', searchEmpty: 'Enter a topic or common synonym to find guided practice.', browseLearning: 'Browse Learning Mode cases', practiseLabel: 'I want to practise', allSkills: 'All skills', startLearning: 'Start Learning Mode', sourceInternet: 'internet required', offlineExplanation: 'This explanation remains available offline.', noCaseTopic: 'No existing case is available for this topic.', noCaseSkill: 'No existing case matches this skill.',
  assessmentIntro: 'Diagnoses and topic clues stay hidden until submission. Only a first attempt on an unseen case can update your prototype skill rating.', noEligible: 'No rating-eligible cases remain', noEligibleText: 'You have already seen every answer key. You can still take practice assessments, or continue with hints and revision in Learning Mode.', goLearning: 'Go to Learning Mode', interpretTracing: 'Interpret the tracing', previouslySeen: 'Previously seen · practice only', unseenEligible: 'Unseen · rating eligible', hintsHidden: 'Hints and answers remain hidden until you submit.', startAssessment: 'Start Assessment Mode', startPracticeAssessment: 'Start practice assessment',
  storedDevice: 'Stored on this device', dashboard: 'Progress dashboard', currentRating: 'Current prototype rating', deviceNote: 'Progress is stored only in this browser on this device. It does not sync and may be lost if browser data is cleared.', ratedCompleted: 'Rated assessments completed', practiceCompleted: 'Guided/practice attempts completed', totalCompleted: 'Total submitted attempts', scoreHistory: 'Score history', noAttempts: 'No attempts recorded yet.', historyNote: 'Guided and repeat scores reflect assisted or previously exposed practice. Score increases there are not evidence of independent improvement.', ratingHistory: 'Rating history', completeUnseen: 'Complete an unseen case assessment to update it.', startingRating: 'Starting rating', skillsPractice: 'Skills needing more practice', noSkillLow: 'No skill is below 80% yet.', completeCaseGuidance: 'Complete a case to see guidance.',
  focusedReview: 'Focused review', reviewMistakes: 'Review mistakes', noMistakes: 'No recorded mistakes yet.', yourAnswer: 'Your answer:', correctAnswer: 'Correct answer:', originalMissing: 'Your original answer was not recorded.', noAnswer: 'No answer selected', practiseSkill: 'Practise this skill', dateUnavailable: 'Date unavailable', legacyCase: 'Legacy case',
  resetProgress: 'Reset progress', resetQuestion: 'Reset all local attempts and return the rating to {rating}?', yesReset: 'Yes, reset progress', cancel: 'Cancel',
  caseScore: '{score}% case score', weightedPoints: '{earned} of {total} weighted points from structured answers. Free text is not scored.', recordedPractice: 'Recorded as practice', learningNoRating: 'Learning Mode does not change the rating.', protectedRating: 'This case’s answer key was already seen, so the rating is protected.', reviseAnswers: 'Revise answers', returnLearning: 'Return to Learning Mode', returnAssessment: 'Return to Assessment Mode', focusedComplete: 'Focused session complete', completedFocused: 'You completed focused practice on {skill}. This is recorded as practice, not evidence of independent mastery.', reviseSkill: 'Revise {skill} and review again', matchesKey: '{skill} matched the answer key.', revise: 'Revise {skill}.', matches: 'Matches', review: 'Review', points: '{points} points',
  interpretationWarning: 'Automated practice feedback—may miss or misunderstand wording.', aboutInterpretation: 'About your interpretation', blankFeedback: 'No written interpretation was entered. Try explaining how the rate, P waves, intervals, axis, and ST/T findings support your conclusion. There is no score or rating penalty.', unrecognised: 'I could not interpret this wording reliably. I have not marked any statement correct or contradictory; use the checklist below to review it yourself.', clearlyStated: 'Clearly stated findings', agreesKey: 'the wording agrees with this case’s answer key.', contradictions: 'Possible contradictions', uncertainStatements: 'Uncertain statements', missingSteps: 'Reasoning steps not clearly recognised:', selfChecklist: 'Self-review checklist', exampleInterpretation: 'Example interpretation', reviseInterpretation: 'Revise your interpretation', revisionNoAttempt: 'Reviewing revised wording does not create an attempt or change your score or rating.', reviewRevision: 'Review revised interpretation', feedbackIncorrect: 'This feedback seems incorrect', flagged: 'Feedback flagged locally', flagSaved: 'Flag saved only in this browser; no data was sent.',
  frenchCheckerLimit: 'The English pattern checker does not interpret French reliably. No automatic finding classification is shown for French writing. Use the translated self-review checklist below.',
  howScoring: 'How scoring works', provisionalWeights: 'These are provisional educational weights, not clinically validated measures of competence.', skill: 'Skill', weight: 'Weight', rationale: 'Rationale',
  offline: 'Offline', offlineText: 'cases, hints, feedback, and saved progress remain available.', updateAvailable: 'App update available.', updatePreserve: 'Your local progress will be preserved.', finishUpdate: 'Finish this attempt to update', applyUpdate: 'Apply update', language: 'Language', storageWarning: 'Browser storage is unavailable or could not be updated. You can continue, but progress may not persist.',
}

const fr = {
  practice: 'Pratique', viewProgress: 'Voir les progrès', backHome: 'Retour à l’accueil', backModes: 'Retour aux modes de pratique', learningMode: 'Mode apprentissage', assessmentMode: 'Mode évaluation', chooseMode: 'Choisir un mode', chooseLearning: 'Choisir le mode apprentissage', chooseAssessment: 'Choisir le mode évaluation',
  nextStep: 'Votre prochaine étape', continueLearning: 'Continuer l’apprentissage', chooseTopic: 'Choisir plutôt un autre sujet', learningDescription: 'Pratiquez avec des indices, des commentaires et la possibilité de réviser.',
  education: 'À des fins éducatives uniquement. Ne pas utiliser pour un diagnostic clinique.', reviewStatus: 'Révision experte du contenu :', notReviewed: 'Pas encore révisé', frenchNotice: 'Les traductions françaises sont provisoires et n’ont pas été révisées par un formateur ECG bilingue.',
  backLearning: 'Retour au mode apprentissage', backAssessment: 'Retour au mode évaluation', foundations: 'Fondamentaux', readSystematically: 'Lisez l’ECG de façon systématique.', learningCaseIntro: 'Utilisez les indices si nécessaire, puis révisez après les commentaires. Vérifiez la fréquence, l’origine sinusale, les intervalles, l’axe et les éléments ST/T.', assessmentCaseIntro: 'Le diagnostic et le sujet restent masqués jusqu’à la soumission. Vérifiez la fréquence, l’origine sinusale, les intervalles, l’axe et les éléments ST/T.',
  schematic: 'ECG éducatif schématique', resting: 'ECG de repos à 12 dérivations', rhythmStrip: 'Dérivation II longue', figureNote: 'Schéma conçu à des fins pédagogiques — il ne s’agit pas d’un enregistrement de patient. Grille horizontale : 1 petit carreau = 40 ms ; étalonnage vertical = 10 mm (1 mV).', expertReview: 'Révision experte :',
  whatSee: 'Que voyez-vous ?', hintsLearning: 'Des indices sont disponibles et la révision n’entraîne aucune pénalité de classement.', hintsAssessment: 'Les indices et les réponses restent masqués jusqu’à la soumission.', notSurePrompt: 'Choisissez « Je ne sais pas » si nécessaire.', chooseFinding: 'Choisissez l’observation la plus appropriée', selectAnswer: 'Sélectionnez une réponse', notSure: 'Je ne sais pas', showHint: 'Afficher l’indice', hideHint: 'Masquer l’indice', tryThis: 'Essayez ceci :',
  explain: 'Expliquez votre interprétation', freeNotScored: 'Ce texte libre n’est pas noté.', placeholder: 'Je pense que cet ECG montre… parce que…', structuredOnly: 'Seules les réponses structurées contribuent au pourcentage pondéré.', submitPractice: 'Soumettre la pratique', submitAssessment: 'Soumettre l’évaluation',
  yourFocus: 'Votre objectif', fullWorkflow: 'Effectuez l’interprétation complète comme d’habitude. Cette séance en mode apprentissage ne peut pas modifier votre classement.', reviewPractice: 'Pratique de révision — ne modifie pas votre classement.',
  topicSearch: 'Que souhaitez-vous apprendre ?', searchTopics: 'Rechercher des sujets ECG', searchPlaceholder: 'Essayez « fréquence lente », « rythme sinusal » ou « rythme »', searchEmpty: 'Saisissez un sujet ou un synonyme courant pour trouver une pratique guidée.', browseLearning: 'Parcourir les cas du mode apprentissage', practiseLabel: 'Je souhaite pratiquer', allSkills: 'Toutes les compétences', startLearning: 'Commencer le mode apprentissage', sourceInternet: 'internet requis', offlineExplanation: 'Cette explication reste disponible hors ligne.', noCaseTopic: 'Aucun cas existant n’est disponible pour ce sujet.', noCaseSkill: 'Aucun cas existant ne correspond à cette compétence.',
  assessmentIntro: 'Les diagnostics et les indices thématiques restent masqués jusqu’à la soumission. Seule la première tentative d’un cas inédit peut modifier votre classement prototype.', noEligible: 'Aucun cas admissible au classement', noEligibleText: 'Vous avez déjà vu tous les corrigés. Vous pouvez refaire des évaluations de pratique ou continuer en mode apprentissage.', goLearning: 'Aller au mode apprentissage', interpretTracing: 'Interpréter le tracé', previouslySeen: 'Déjà vu · pratique uniquement', unseenEligible: 'Inédit · admissible au classement', hintsHidden: 'Les indices et les réponses restent masqués jusqu’à la soumission.', startAssessment: 'Commencer le mode évaluation', startPracticeAssessment: 'Commencer une évaluation de pratique',
  storedDevice: 'Stocké sur cet appareil', dashboard: 'Tableau de progression', currentRating: 'Classement prototype actuel', deviceNote: 'La progression est stockée uniquement dans ce navigateur sur cet appareil. Elle n’est pas synchronisée et peut être perdue si les données du navigateur sont effacées.', ratedCompleted: 'Évaluations classées terminées', practiceCompleted: 'Tentatives guidées/de pratique terminées', totalCompleted: 'Total des tentatives soumises', scoreHistory: 'Historique des scores', noAttempts: 'Aucune tentative enregistrée.', historyNote: 'Les scores guidés et répétés reflètent une pratique assistée ou déjà exposée. Leur augmentation ne prouve pas une amélioration indépendante.', ratingHistory: 'Historique du classement', completeUnseen: 'Terminez l’évaluation d’un cas inédit pour le modifier.', startingRating: 'Classement initial', skillsPractice: 'Compétences à travailler', noSkillLow: 'Aucune compétence n’est actuellement inférieure à 80 %.', completeCaseGuidance: 'Terminez un cas pour obtenir des conseils.',
  focusedReview: 'Révision ciblée', reviewMistakes: 'Revoir les erreurs', noMistakes: 'Aucune erreur enregistrée.', yourAnswer: 'Votre réponse :', correctAnswer: 'Réponse correcte :', originalMissing: 'Votre réponse initiale n’a pas été enregistrée.', noAnswer: 'Aucune réponse sélectionnée', practiseSkill: 'Pratiquer cette compétence', dateUnavailable: 'Date indisponible', legacyCase: 'Cas hérité',
  resetProgress: 'Réinitialiser la progression', resetQuestion: 'Réinitialiser toutes les tentatives locales et ramener le classement à {rating} ?', yesReset: 'Oui, réinitialiser', cancel: 'Annuler',
  caseScore: 'Score du cas : {score} %', weightedPoints: '{earned} points pondérés sur {total} pour les réponses structurées. Le texte libre n’est pas noté.', recordedPractice: 'Enregistré comme pratique', learningNoRating: 'Le mode apprentissage ne modifie pas le classement.', protectedRating: 'Le corrigé de ce cas a déjà été vu ; le classement est donc protégé.', reviseAnswers: 'Réviser les réponses', returnLearning: 'Retour au mode apprentissage', returnAssessment: 'Retour au mode évaluation', focusedComplete: 'Séance ciblée terminée', completedFocused: 'Vous avez terminé une pratique ciblée sur {skill}. Elle est enregistrée comme pratique et ne constitue pas une preuve de maîtrise indépendante.', reviseSkill: 'Réviser {skill} et vérifier à nouveau', matchesKey: '{skill} correspond au corrigé.', revise: 'Réviser {skill}.', matches: 'Conforme', review: 'À revoir', points: '{points} points',
  interpretationWarning: 'Commentaire automatisé de pratique — peut manquer ou mal comprendre certaines formulations.', aboutInterpretation: 'À propos de votre interprétation', blankFeedback: 'Aucune interprétation écrite n’a été saisie. Expliquez comment la fréquence, les ondes P, les intervalles, l’axe et les éléments ST/T étayent votre conclusion. Aucune pénalité de score ou de classement.', unrecognised: 'Je n’ai pas pu interpréter cette formulation de manière fiable. Utilisez la liste d’auto-évaluation ci-dessous.', clearlyStated: 'Constatations clairement énoncées', agreesKey: 'la formulation correspond au corrigé de ce cas.', contradictions: 'Contradictions possibles', uncertainStatements: 'Énoncés incertains', missingSteps: 'Étapes de raisonnement non clairement reconnues :', selfChecklist: 'Liste d’auto-évaluation', exampleInterpretation: 'Exemple d’interprétation', reviseInterpretation: 'Réviser votre interprétation', revisionNoAttempt: 'La révision du texte ne crée pas de tentative et ne modifie ni le score ni le classement.', reviewRevision: 'Relire l’interprétation révisée', feedbackIncorrect: 'Ce commentaire semble incorrect', flagged: 'Commentaire signalé localement', flagSaved: 'Signalement enregistré uniquement dans ce navigateur ; aucune donnée n’a été envoyée.',
  frenchCheckerLimit: 'Le vérificateur de motifs anglais ne comprend pas le français de manière fiable. Aucune classification automatique des constatations n’est affichée pour un texte français. Utilisez la liste d’auto-évaluation traduite ci-dessous.',
  howScoring: 'Comment fonctionne la notation', provisionalWeights: 'Ces pondérations éducatives sont provisoires et ne sont pas des mesures de compétence validées cliniquement.', skill: 'Compétence', weight: 'Pondération', rationale: 'Justification',
  offline: 'Hors ligne', offlineText: 'les cas, indices, commentaires et progrès enregistrés restent disponibles.', updateAvailable: 'Mise à jour disponible.', updatePreserve: 'Votre progression locale sera conservée.', finishUpdate: 'Terminez cette tentative pour mettre à jour', applyUpdate: 'Appliquer la mise à jour', language: 'Langue', storageWarning: 'Le stockage du navigateur est indisponible ou n’a pas pu être mis à jour. Vous pouvez continuer, mais la progression risque de ne pas être conservée.',
}

export const dictionaries = { en, fr }
export function translate(language, key, values = {}) {
  let value = dictionaries[language]?.[key] ?? en[key] ?? key
  Object.entries(values).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)) })
  return value
}
export function I18nProvider({ value, children }) { return <I18nContext.Provider value={value}>{children}</I18nContext.Provider> }
export function useI18n() { return useContext(I18nContext) }

const skillFr = { rate: 'Fréquence', rhythm: 'Rythme', axis: 'Axe QRS frontal', pWaves: 'Ondes P', pr: 'Intervalle PR', qrs: 'Durée du QRS', stt: 'Éléments ST/T' }
const diagnosisFr = { 'Normal sinus rhythm': 'Rythme sinusal normal', 'Sinus bradycardia': 'Bradycardie sinusale', 'Sinus tachycardia': 'Tachycardie sinusale' }
const optionFr = {
  'Regular sinus bradycardia': 'Bradycardie sinusale régulière', 'Regular sinus rhythm': 'Rythme sinusal régulier', 'Regular sinus tachycardia': 'Tachycardie sinusale régulière',
  'Left axis deviation': 'Déviation axiale gauche', 'Normal axis': 'Axe normal', 'Right axis deviation': 'Déviation axiale droite',
  'Absent': 'Absentes', 'Present, sinus morphology, one before each QRS': 'Présentes, morphologie sinusale, une avant chaque QRS', 'Present but unrelated to QRS complexes': 'Présentes mais sans relation avec les complexes QRS',
  'ST elevation': 'Sus-décalage du segment ST', 'ST depression with T-wave inversion': 'Sous-décalage ST avec inversion de l’onde T', 'No significant ST/T abnormality': 'Aucune anomalie ST/T significative',
}
export function localizeOption(label, language) {
  if (typeof label !== 'string') return ''
  if (language === 'en') return label
  if (optionFr[label]) return optionFr[label]
  return label.replace(' (normal)', ' (normal)').replace(' (short)', ' (court)').replace(' (prolonged)', ' (prolongé)').replace(' (narrow)', ' (fin)').replace(' (wide)', ' (large)')
}
export function localizeSkill(id, language) { return language === 'fr' ? skillFr[id] : ({ rate: 'Rate', rhythm: 'Rhythm', axis: 'Frontal QRS axis', pWaves: 'P waves', pr: 'PR interval', qrs: 'QRS duration', stt: 'ST/T findings' }[id] || id) }
export function localizeDiagnosis(value, language) { return language === 'fr' ? diagnosisFr[value] || value : value }

export function localizeQuestion(caseData, question, language) {
  if (language === 'en') return question
  const hints = {
    rate: 'À 25 mm/s, un grand carreau correspond à 0,2 seconde. Comptez les grands carreaux entre deux ondes R, puis calculez 300 ÷ ce nombre.',
    rhythm: 'Comparez les intervalles RR, puis recherchez une onde P constante avant chaque QRS et un QRS après chaque onde P. Classez ensuite la fréquence.',
    axis: 'Utilisez la méthode des quadrants : examinez la direction nette du QRS dans les dérivations I et aVF.',
    pWaves: 'La dérivation II montre généralement bien les ondes P sinusales. Vérifiez leur direction, leur forme et leur relation avec chaque QRS.',
    pr: 'Mesurez du début de l’onde P au début du QRS. Chaque petit carreau représente 40 ms à 25 mm/s.',
    qrs: 'Mesurez de la première déflexion du QRS à la fin de l’onde S. Chaque petit carreau représente 40 ms.',
    stt: 'Utilisez le segment TP comme ligne de base. Comparez-le au segment ST, puis examinez la direction des ondes T.',
  }
  const explanations = {
    rate: `Les ondes R sont espacées de ${caseData.rrMs / 200} grands carreaux : 300 ÷ ${caseData.rrMs / 200} = ${caseData.rate} bpm. L’intervalle RR généré est exactement de ${caseData.rrMs} ms.`,
    rhythm: `Les intervalles RR sont égaux et des ondes P positives précèdent chaque QRS en dérivation II avec un intervalle PR fixe. La fréquence correspond à un ${localizeDiagnosis(caseData.diagnosis, 'fr').toLowerCase()}.`,
    axis: 'Le QRS est principalement positif dans les dérivations I et aVF. L’axe frontal moyen modélisé est d’environ +60°, dans la plage normale adulte.',
    pWaves: 'Des ondes P uniformes et positives sont visibles en dérivation II avant chaque QRS ; elles sont négatives en aVR, comme attendu pour un vecteur sinusal.',
    pr: `Du début de l’onde P au début du QRS, on compte ${caseData.prMs / 40} petits carreaux : ${caseData.prMs / 40} × 40 ms = ${caseData.prMs} ms, dans la plage habituelle de 120 à 200 ms.`,
    qrs: `Le QRS généré couvre ${caseData.qrsMs / 40} petits carreaux : ${caseData.qrsMs / 40} × 40 ms = ${caseData.qrsMs} ms ; il est fin.`,
    stt: 'Les segments ST reviennent à la ligne de base modélisée sans déplacement. Les ondes T sont positives dans les dérivations attendues et inversées uniquement en aVR.',
  }
  return { ...question, label: localizeSkill(question.id, language), hint: hints[question.id], explanation: explanations[question.id] }
}

export function frenchExample(caseData) {
  return `Cet ECG montre un ${localizeDiagnosis(caseData.diagnosis, 'fr').toLowerCase()} à ${caseData.rate} bpm. Le rythme est régulier, avec des ondes P sinusales avant chaque QRS. L’axe est normal, l’intervalle PR mesure ${caseData.prMs} ms et le QRS est fin à ${caseData.qrsMs} ms. Il n’y a pas d’anomalie ST/T significative.`
}
export const frenchChecklist = ['Indiquez la fréquence et le rythme.', 'Décrivez les ondes P et leur relation avec les complexes QRS.', 'Indiquez l’axe, l’intervalle PR et la durée du QRS.', 'Décrivez les anomalies ST/T significatives ou leur absence.']
