import { useState } from 'react'
import { createReminderIcs } from './calendarReminder.js'
import { useI18n } from './i18n.jsx'

const copy = {
  en: { open: 'Remind me to practise this', date: 'Start date', time: 'Local time', frequency: 'Frequency', end: 'End date', once: 'Once', daily: 'Daily', weekly: 'Weekly', ten: 'Daily for 10 days', download: 'Download calendar reminder', cancel: 'Cancel', import: 'Import this file into your calendar. Reminder alerts depend on your calendar settings.', manual: 'Downloading does not automatically schedule a reminder.', starts: 'Reminders start on the chosen date. Tete cannot detect missed calendar events or automatically stop imported reminders when practice resumes.', resumed: 'Started practising again? You can remove the remaining reminders from your calendar.', neutral: 'Missing or dismissing reminders never affects scores or ratings.', success: 'Calendar file downloaded. Import it into your calendar to schedule the reminder.', invalidDateTime: 'Choose a valid date and local time.', futureRequired: 'Choose a future date and time.', invalidFrequency: 'Choose a supported frequency.', invalidEndDate: 'Choose an end date on or after the start date.', invalidTarget: 'This reminder target is not supported.', downloadFailed: 'The calendar file could not be downloaded. Nothing was scheduled.' },
  fr: { open: 'Me rappeler de pratiquer ce sujet', date: 'Date de début', time: 'Heure locale', frequency: 'Fréquence', end: 'Date de fin', once: 'Une fois', daily: 'Tous les jours', weekly: 'Chaque semaine', ten: 'Tous les jours pendant 10 jours', download: 'Télécharger le rappel calendrier', cancel: 'Annuler', import: 'Importez ce fichier dans votre calendrier. Les alertes dépendent des réglages de votre calendrier.', manual: 'Le téléchargement ne programme pas automatiquement un rappel.', starts: 'Les rappels commencent à la date choisie. Tete ne peut pas détecter les rappels manqués ni arrêter automatiquement les rappels importés lorsque vous reprenez la pratique.', resumed: 'Vous avez repris la pratique ? Vous pouvez supprimer les rappels restants de votre calendrier.', neutral: 'Manquer ou ignorer un rappel ne modifie jamais les scores ni le classement.', success: 'Fichier calendrier téléchargé. Importez-le pour programmer le rappel.', invalidDateTime: 'Choisissez une date et une heure locale valides.', futureRequired: 'Choisissez une date et une heure futures.', invalidFrequency: 'Choisissez une fréquence prise en charge.', invalidEndDate: 'Choisissez une date de fin égale ou postérieure à la date de début.', invalidTarget: 'Cette cible de rappel n’est pas prise en charge.', downloadFailed: 'Le fichier calendrier n’a pas pu être téléchargé. Rien n’a été programmé.' },
  sw: { open: 'Nikumbushe kufanya zoezi hili', date: 'Tarehe ya kuanza', time: 'Saa ya eneo lako', frequency: 'Marudio', end: 'Tarehe ya mwisho', once: 'Mara moja', daily: 'Kila siku', weekly: 'Kila wiki', ten: 'Kila siku kwa siku 10', download: 'Pakua ukumbusho wa kalenda', cancel: 'Ghairi', import: 'Ingiza faili hii kwenye kalenda yako. Alerts za ukumbusho hutegemea mipangilio ya kalenda yako.', manual: 'Kupakua hakupangi ukumbusho moja kwa moja.', starts: 'Vikumbusho huanza tarehe uliyochagua. Tete haiwezi kutambua vikumbusho vilivyokosekana au kusimamisha vilivyoingizwa unapofanya mazoezi tena.', resumed: 'Umeanza kufanya mazoezi tena? Unaweza kuondoa vikumbusho vilivyobaki kwenye kalenda yako.', neutral: 'Kukosa au kufunga ukumbusho hakubadilishi alama au rating.', success: 'Faili ya kalenda imepakuliwa. Ingiza kwenye kalenda ili kupanga ukumbusho.', invalidDateTime: 'Chagua tarehe na saa halali za eneo lako.', futureRequired: 'Chagua tarehe na saa zijazo.', invalidFrequency: 'Chagua marudio yanayokubalika.', invalidEndDate: 'Chagua tarehe ya mwisho iliyo sawa au baada ya tarehe ya kuanza.', invalidTarget: 'Lengo hili la ukumbusho halikubaliki.', downloadFailed: 'Faili ya kalenda haikuweza kupakuliwa. Hakuna kilichopangwa.' },
}

copy.en.import = 'Learning works offline. Calendar reminders depend on your calendar app. Import this file into your calendar to add the reminder.'
copy.fr.import = 'L’apprentissage fonctionne hors ligne. Les rappels de calendrier dépendent de votre application de calendrier. Importez ce fichier dans votre calendrier pour ajouter le rappel.'
copy.sw.import = 'Kujifunza hufanya kazi bila intaneti. Vikumbusho vya kalenda hutegemea programu yako ya kalenda. Ingiza faili hii kwenye kalenda yako ili kuongeza ukumbusho.'

export default function ReminderForm({ stableId, title, url, completed = false }) {
  const { language } = useI18n(); const c = copy[language] || copy.en
  const [open, setOpen] = useState(false); const [frequency, setFrequency] = useState('once'); const [message, setMessage] = useState('')
  const needsEnd = frequency === 'daily' || frequency === 'weekly'
  const submit = (event) => {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    const result = createReminderIcs({ stableId, title, url, invitation: language === 'fr' ? 'Prenez cinq minutes pour pratiquer cette compétence ECG avec Tete.' : language === 'sw' ? 'Tumia dakika tano kufanya zoezi hili la ECG katika Tete.' : 'Take five minutes to practise this ECG skill with Tete.', date: form.get('date'), time: form.get('time'), frequency, endDate: form.get('endDate') })
    if (!result.ok) { setMessage(result.code); return }
    try { const blob = new Blob([result.ics], { type: 'text/calendar;charset=utf-8' }); const href = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = href; link.download = `tete-${stableId}-reminder.ics`; document.body.append(link); link.click(); link.remove(); URL.revokeObjectURL(href); setMessage('success') } catch { setMessage('downloadFailed') }
  }
  if (!open) return <button type="button" className="text-button reminder-toggle" onClick={() => setOpen(true)} aria-expanded="false">{c.open}</button>
  return <form className="reminder-form" onSubmit={submit}><h4>{c.open}</h4><p>{c.import}</p><p>{c.manual}</p><div className="reminder-grid"><label>{c.date}<input name="date" type="date" required /></label><label>{c.time}<input name="time" type="time" required /></label><label>{c.frequency}<select value={frequency} onChange={(event) => { setFrequency(event.target.value); setMessage('') }}><option value="once">{c.once}</option><option value="daily">{c.daily}</option><option value="weekly">{c.weekly}</option><option value="daily-10">{c.ten}</option></select></label>{needsEnd && <label>{c.end}<input name="endDate" type="date" required /></label>}</div><p>{c.starts}</p>{completed && <p className="notice">{c.resumed}</p>}<p>{c.neutral}</p>{message && <p role={message === 'success' ? 'status' : 'alert'} className={message === 'success' ? 'notice' : 'storage-warning'}>{c[message]}</p>}<div className="reminder-actions"><button type="submit" className="secondary-button">{c.download}</button><button type="button" className="text-button" onClick={() => { setOpen(false); setMessage('') }}>{c.cancel}</button></div></form>
}
